In [121]:
import numpy as np
import tensorflow as tf
from numpy import genfromtxt
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

my_data = genfromtxt('Stars.csv', delimiter=',', skip_header=1)

features = my_data[:,:4]
labels = np.array(tf.one_hot(my_data[:,-1], 6))

train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size=0.4, shuffle=True)

label_integers = np.argmax(train_labels, axis=1)
class_weights = compute_class_weight('balanced', classes=np.unique(label_integers), y=label_integers)
d_class_weights = dict(enumerate(class_weights))

[[3.06800e+03 2.40000e-03 1.70000e-01 ...         nan         nan
  0.00000e+00]
 [3.04200e+03 5.00000e-04 1.54200e-01 ...         nan         nan
  0.00000e+00]
 [2.60000e+03 3.00000e-04 1.02000e-01 ...         nan         nan
  0.00000e+00]
 ...
 [8.82900e+03 5.37493e+05 1.42300e+03 ...         nan         nan
  5.00000e+00]
 [9.23500e+03 4.04940e+05 1.11200e+03 ...         nan         nan
  5.00000e+00]
 [3.78820e+04 2.94903e+05 1.78300e+03 ...         nan         nan
  5.00000e+00]]
[[ 3.06800e+03  2.40000e-03  1.70000e-01  1.61200e+01]
 [ 3.04200e+03  5.00000e-04  1.54200e-01  1.66000e+01]
 [ 2.60000e+03  3.00000e-04  1.02000e-01  1.87000e+01]
 [ 2.80000e+03  2.00000e-04  1.60000e-01  1.66500e+01]
 [ 1.93900e+03  1.38000e-04  1.03000e-01  2.00600e+01]
 [ 2.84000e+03  6.50000e-04  1.10000e-01  1.69800e+01]
 [ 2.63700e+03  7.30000e-04  1.27000e-01  1.72200e+01]
 [ 2.60000e+03  4.00000e-04  9.60000e-02  1.74000e+01]
 [ 2.65000e+03  6.90000e-04  1.10000e-01  1.74500e+01]
 [ 2.70000e+0

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential(
    [
        layers.Dense(64, activation="relu", input_shape=(4,)),
        layers.Dense(128, activation="relu"),
        layers.Dense(64, activation="relu"),
        layers.Dense(6, activation="softmax"),
    ]
)


In [120]:
from keras.callbacks import ReduceLROnPlateau

model.compile(optimizer=keras.optimizers.Adam(learning_rate=1e-4), loss=keras.losses.CategoricalCrossentropy(), metrics=[keras.metrics.CategoricalAccuracy()])
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=0.001)
model.fit(x=train_features, y=train_labels, validation_data=(test_features, test_labels), callbacks=[reduce_lr], verbose=2, shuffle=True, batch_size=256, epochs=2000, class_weight=d_class_weights)

Epoch 1/2000
1/1 - 1s - loss: 16301.4219 - categorical_accuracy: 0.2014 - val_loss: 18595.0391 - val_categorical_accuracy: 0.1771 - lr: 1.0000e-04 - 980ms/epoch - 980ms/step
Epoch 2/2000
1/1 - 0s - loss: 15589.7451 - categorical_accuracy: 0.2014 - val_loss: 17741.6152 - val_categorical_accuracy: 0.1771 - lr: 1.0000e-04 - 34ms/epoch - 34ms/step
Epoch 3/2000
1/1 - 0s - loss: 14880.8555 - categorical_accuracy: 0.2014 - val_loss: 16891.6777 - val_categorical_accuracy: 0.1771 - lr: 1.0000e-04 - 35ms/epoch - 35ms/step
Epoch 4/2000
1/1 - 0s - loss: 14175.4482 - categorical_accuracy: 0.2014 - val_loss: 16044.7646 - val_categorical_accuracy: 0.1771 - lr: 1.0000e-04 - 34ms/epoch - 34ms/step
Epoch 5/2000
1/1 - 0s - loss: 13472.4980 - categorical_accuracy: 0.2014 - val_loss: 15201.1514 - val_categorical_accuracy: 0.1771 - lr: 1.0000e-04 - 36ms/epoch - 36ms/step
Epoch 6/2000
1/1 - 0s - loss: 12771.3076 - categorical_accuracy: 0.2014 - val_loss: 14359.9873 - val_categorical_accuracy: 0.1771 - lr: 1.

KeyboardInterrupt: 